title: 		NEON Git & GitHub Training
description: 	A test development site that will host education materials that support the use of big data in science.
#Comment out url when working locally to resolve base urls correctly ok
#use this when pushing to git for live version

url:           http://neonscience.github.io/NEONgitTraining
baseurl:       http://neonscience.github.io/NEONgitTraining

#use this when working locally
#url: http://localhost:4000
#baseurl:

#disqus_shortname:
# Social networking links are used in author-bio sidebar. Update and remove as you like.

# Owner/author information
owner: 		
  name: NEON
  avatar: profilePic_circle.png
  bio: "We are devoted to open data, open source and facilitating the use of Big Data in science and education."
  email: 
  twitter: "NEON_Sci"
  github: "NEONScience"
  youtube: 

# For Google Authorship https://plus.google.com/authorship
# google_plus:    "MichaelRoseDesign"

# Analytics and webmaster tools stuff goes here
google_analytics:   
#google_verify:      UQj93ERU9zgECodaaXgVpkjrFn9UrDMEzVamacSoQ8Y
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
#bing_verify:        D81F4C18A6CB3018F64D7C827D953DFD

category: [using lidar data, working with field data, zcarbon links]
categories: [using lidar data, working with field data, zcarbon links]
# Links to include in top navigation
# For external links add external: true
links:  
  - title: All Posts
    url: /posts/
  
  - title: About
    url: /about/
    
  - title: NEON Website
    url: http://neonscience.org
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
# turning off pygments for the time being
#pygments:    true
#highlighter: pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

#markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
